quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=test
quarkus.datasource.password=test
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/test
quarkus.hibernate-orm.database.generation=update
